### PR TITLE
polish usage docs

### PR DESCRIPTION
**Pull request by xh3b4sd**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

## Context 

Based on https://github.com/giantswarm/awscnfm/pull/208. Just polishing more docs.

### CODE REVIEW

**Review by calvix — APPROVED** [review]
AnyConv com__polish

**Comment by xh3b4sd** [comment]
What does that mean? Is that a flag? 🙈 😅

**Comment by xh3b4sd** [comment]
Ok, that was another `cleanupenis`. 😂

**Comment by calvix** [comment]
`polish` was right there :trollface:

**Comment by anvddriesch** [comment]
When I saw this in my inbox my first thought was also "why do we need docs in polish?" :D

**Pull request merged**
