### PR TITLE
insert-action-08-kiam-test-to-cl001

### PR DESCRIPTION
**Pull request by calvix**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

## Content
 inserting ac008 for kiam testing to the cl001
some files moving had to be done

towards https://github.com/giantswarm/giantswarm/issues/13229

### CODE REVIEW

**Comment by xh3b4sd** [comment]
For me this is almost impossible to review. In theory you could have split PRs to make it more comprehensible. Though I am not blocking here and when this is what you need go for it.

**Comment by calvix** [comment]
how to split this?

**Comment by calvix** [comment]
there are basically no changes other than moving ac008 -> ac 009, ac009 -> acc010 and adding empty ac 008

No new real code

**Comment by xh3b4sd** [comment]
Ok cool. I did not follow there is no new code written by yourself. When this is just moving and generating it should be fine.

**Review by xh3b4sd — APPROVED** [review]

**Pull request merged**
